# Generated by Django 4.2.27 on 2026-01-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='replied',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='website_url',
            field=models.URLField(default='http://127.0.0.1:8000/', help_text='Live website link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='animation',
            field=models.CharField(blank=True, help_text='Optional animation class', max_length=100),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='animation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='company',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
